version: "2"

networks:
  gitea:
    external: false

services:
  server:
   image: gitea/gitea:latest
   environment:
     - USER_UID=1000
     - USER_GID=1000
     - DB_TYPE=mysql
     - DB_HOST=db:3306
     - DB_NAME=gitea
     - DB_USER=gitea
     - DB_PASSWD=123456
     - APP_NAME=My_Git_Server
     - DISABLE_SSH=true
     - DISABLE_REGISTRATION=true
     - DOMAIN=git.local
   restart: always
   networks:
     - gitea
   volumes:
     - ./gitea:/data
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
   ports:
     - "3000:3000"
     - "222:22"
   depends_on:
     - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql
